using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AwesomeAssertions;
using CSharpFunctionalExtensions;
using Gp4Net.CardEmulator.Core;
using Gp4Net.CardEmulator.Functional;
using Gp4Net.Constants;
using Gp4Net.Core;
using Gp4Net.Domain;
using Gp4Net.Domain.Commands;
using Gp4Net.Domain.Keys;
using Gp4Net.Domain.Security;
using Gp4Net.Pipeline;
using Gp4Net.Services;
using Gp4Net.Transport;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.DependencyInjection;
using Gp4Net.Domain.Protocol;
using NUnit.Framework;
using Org.BouncyCastle.Crypto.Engines;

namespace Gp4Net.Tests.Integration;

/// <summary>
/// Comprehensive integration tests for virtual card secure channel establishment through GP pipeline.
/// Tests real cryptographic operations end-to-end without mocks or trace replay.
/// Validates GP 2.3.1 compliance for SCP02 and SCP03 protocols.
/// </summary>
[TestFixture]
[Category("Integration")]
[Category("VirtualCard")]
[Category("Pipeline")]
public class VirtualCardPipelineIntegrationTests
{
    private ILogger _logger;
    private VirtualCard _virtualCard;
    private IApduTransport _transport;
    private ICardChannel _channel;
    private PreloadedRngService _deterministicRng;

    [SetUp]
    public void SetUp()
    {
        _logger = Microsoft.Extensions.Logging.Abstractions.NullLogger.Instance;

        // Create deterministic entropy for reproducible SCP02 tests
        // Host challenge: 01 02 03 04 05 06 07 08 (fixed in GenerateHostChallenge)
        // Card challenge: 09 0A 0B 0C 0D 0E (bytes 8-13, generated by virtual card)
        // Remaining: 0F 10 11... (bytes 14+, for other cryptographic operations)
        byte[] deterministicEntropy = Enumerable.Range(1, 64)
            .Select(i => (byte)i)
            .ToArray(); // Sequential values: 01, 02, 03, etc.

        // Create virtual card with entropy starting from position 8 (after host challenge)
        // This ensures card challenge will be 09 0A 0B 0C 0D 0E instead of 01 02 03 04 05 06
        byte[] virtualCardEntropy = deterministicEntropy.Skip(8).ToArray();

        _deterministicRng = PreloadedRngService.Create(deterministicEntropy)
            .Match(
                rng => rng,
                error => PreloadedRngService.Create([0x01]).GetValueOrDefault(null!)
            );

        // Create virtual card with entropy that starts at position 8
        _virtualCard = VirtualCardTestBuilder.P71CardWithEntropy(virtualCardEntropy)
            .Match(
                card => card,
                error => VirtualCardTestBuilder.P71Card()
            );

        _transport = new VirtualCardTransport(_virtualCard);
        _channel = new VirtualCardChannel(_virtualCard);
        _lastDerivedSessionKeys = Maybe<SessionKeys>.None; // Reset session keys
    }

    [TearDown]
    public void TearDown()
    {
        _virtualCard?.Reset();
    }

    /// <summary>
    /// Tests complete SCP02 secure channel establishment through GP pipeline.
    /// Verifies: SELECT → INITIALIZE UPDATE → EXTERNAL AUTHENTICATE → protected commands.
    /// </summary>
    [Test]
    public async Task SCP02_SecureChannel_EstablishmentThroughPipeline_ShouldSucceed()
    {
        // Arrange - Create pipeline environment with virtual card
        CommandProcessing.CommandEnvironment environment = CreatePipelineEnvironment();

        // Step 1: SELECT ISD - Required before secure channel establishment
        Result<CommandResponse, SmartCardError> selectResult = await ExecuteSelectIsd();

        selectResult.Match(
            onSuccess: result =>
            {
                _ = result.StatusWord.Should().Be(StatusWords.Success);
                _ = _virtualCard.IsSelected.Should().BeTrue("Card should be in selected state after SELECT");
            },
            onFailure: error =>
            {
                Assert.Fail($"SELECT ISD should succeed: {error}");
            });

        // Step 2: INITIALIZE UPDATE - Start secure channel establishment
        byte[] hostChallenge = GenerateHostChallenge();
        Result<CommandResponse, SmartCardError> initUpdateResult = await ExecuteInitializeUpdate(hostChallenge);

        byte[] initResponse = null;
        byte keyVersion = 0;
        byte scpId = 0;
        byte[] cardChallenge = null;
        byte[] cardCryptogram = null;
        byte[] sequenceCounter = null;

        initUpdateResult.Match(
            onSuccess: result =>
            {
                _ = result.StatusWord.Should().Be(StatusWords.Success);

                // Use proper InitializeUpdateResponse parser instead of raw array slicing
                Result<InitializeUpdateResponse, SmartCardError> parseResult = InitializeUpdateResponse.Parse(result.Data);
                parseResult.Match(
                    onSuccess: parsed =>
                    {
                        _ = parsed.ScpId.Should().Be((byte)0x02, "P71 cards use SCP02 protocol");
                        _ = parsed.KeyVersion.Should().BeOneOf([0x01, 0xFF], "Key version should be 01 or FF for P71");

                        initResponse = result.Data;
                        keyVersion = parsed.KeyVersion;
                        scpId = parsed.ScpId;
                        cardChallenge = parsed.CardChallenge; // This will be 6 bytes for SCP02
                        cardCryptogram = parsed.CardCryptogram;
                        sequenceCounter = parsed.SequenceCounter;
                    },
                    onFailure: parseError =>
                    {
                        Assert.Fail($"Failed to parse INITIALIZE UPDATE response: {parseError}");
                    });
            },
            onFailure: error =>
            {
                Assert.Fail($"INITIALIZE UPDATE should succeed: {error}");
            });

        // Step 3: Derive session keys using real cryptographic operations
        SessionKeys? sessionKeys = DeriveSessionKeys(keyVersion, hostChallenge, cardChallenge).Match(
            onSuccess: keys =>
            {
                // Store session keys for later use in EXTERNAL AUTHENTICATE
                _lastDerivedSessionKeys = Maybe<SessionKeys>.From(keys);
                return keys;
            },
            onFailure: error =>
            {
                Assert.Fail($"Session key derivation should succeed: {error}");
                return default;
            });

        // Step 4: Calculate host cryptogram and verify card cryptogram
        byte[]? hostCryptogram = CalculateAndVerifyCryptograms(
            sessionKeys, hostChallenge, cardChallenge, cardCryptogram, sequenceCounter).Match(
            onSuccess: crypto => crypto,
            onFailure: error =>
            {
                Assert.Fail($"Cryptogram calculation should succeed: {error}");
                return default;
            });

        // Step 5: EXTERNAL AUTHENTICATE - Complete secure channel establishment
        TestContext.Out.WriteLine($"🔍 Sending host cryptogram: {Convert.ToHexString(hostCryptogram)}");
        Result<CommandResponse, SmartCardError> extAuthResult = await ExecuteExternalAuthenticate(hostCryptogram);

        extAuthResult.Match(
            onSuccess: result =>
            {
                _ = result.StatusWord.Should().Be(StatusWords.Success);
                _ = _virtualCard.IsSecureChannelEstablished.Should().BeTrue("Secure channel should be established");
            },
            onFailure: error =>
            {
                TestContext.Out.WriteLine($"❌ EXTERNAL AUTHENTICATE failed with: {error}");
                Assert.Fail($"EXTERNAL AUTHENTICATE should succeed: {error}");
            });

        // Step 6: Verify protected commands work with established secure channel
        await VerifyProtectedCommandsWork();

        TestContext.Out.WriteLine("✅ SCP02 secure channel established successfully through pipeline");
    }

    /// <summary>
    /// Tests SCP03 secure channel establishment using proper GP architecture.
    /// Uses SecureChannelManager (host-side) with VirtualCard transport (card-side).
    /// </summary>
    [Test]
    public async Task SCP03_SecureChannel_EstablishmentThroughPipeline_ShouldSucceed()
    {
        // Arrange - Use SCP03-capable card with proper architecture
        _virtualCard = VirtualCardTestBuilderExtensions.Scp03Card();
        _transport = new VirtualCardTransport(_virtualCard);
        _channel = new VirtualCardChannel(_virtualCard);

        // Get SCP03 key set from virtual card configuration for host-side processing
        Scp03KeySet? keySet = GetScp03KeySetFromVirtualCard().Match(
            onSuccess: keys =>
            {
                TestContext.Out.WriteLine($"🔍 HOST SIDE - Retrieved SCP03 key set:");
                TestContext.Out.WriteLine($"🔍 ENC Key: {Convert.ToHexString(keys.EncKey)} ({keys.EncKey.Length} bytes)");
                TestContext.Out.WriteLine($"🔍 MAC Key: {Convert.ToHexString(keys.MacKey)} ({keys.MacKey.Length} bytes)");
                TestContext.Out.WriteLine($"🔍 DEK Key: {Convert.ToHexString(keys.DekKey)} ({keys.DekKey.Length} bytes)");
                TestContext.Out.WriteLine($"🔍 Key Version: 0x{keys.KeyVersion:X2}");
                return keys;
            },
            onFailure: error =>
            {
                Assert.Fail($"Virtual card should have SCP03 key set configured: {error.Message}");
                return default;
            });

        // Use proper GP architecture: SecureChannelManager for host-side processing
        DefaultChallengeGenerator challengeGenerator = new DefaultChallengeGenerator(Microsoft.Extensions.Logging.Abstractions.NullLogger<DefaultChallengeGenerator>.Instance);

        // Create a service provider with ALL required dependencies for SecureChannelProtocolFactory
        ServiceCollection serviceCollection = new ServiceCollection();
        _ = serviceCollection.AddSingleton<Gp4Net.Cryptography.IKeyDerivationService, KeyDerivationService>();
        _ = serviceCollection.AddSingleton<CryptogramService>();
        _ = serviceCollection.AddLogging();
        ServiceProvider serviceProvider = serviceCollection.BuildServiceProvider();

        TestContext.Out.WriteLine($"🔍 HOST SIDE - Service provider configured with IKeyDerivationService and CryptogramService");
        var protocolFactory = new SecureChannelProtocolFactory(serviceProvider, Microsoft.Extensions.Logging.Abstractions.NullLogger<SecureChannelProtocolFactory>.Instance);

        var secureChannelManager = new SecureChannelManager(
            protocolFactory, challengeGenerator, Microsoft.Extensions.Logging.Abstractions.NullLogger<SecureChannelManager>.Instance);

        // Step 1: SELECT ISD (still needed for card to be in proper state)
        Result<CommandResponse, SmartCardError> selectResult = await ExecuteSelectIsd();
        _ = selectResult.IsSuccess.Should().BeTrue("SELECT ISD should succeed");

        // Step 2: Establish secure channel using proper GP architecture
        SecurityLevel securityLevel = SecurityLevel.CMac; // SCP03 with C-MAC
        TestContext.Out.WriteLine($"🔍 HOST SIDE - About to establish secure channel with SecureChannelManager");
        TestContext.Out.WriteLine($"🔍 HOST SIDE - Security Level: {securityLevel}");

        Result<SecureChannelState, SmartCardError> secureChannelResult;
        try
        {
            TestContext.Out.WriteLine($"🔍 HOST SIDE - Calling SecureChannelManager.EstablishAsync");
            secureChannelResult = await secureChannelManager.EstablishAsync(
                _channel, _transport, keySet, securityLevel, CancellationToken.None);
            TestContext.Out.WriteLine($"🔍 HOST SIDE - SecureChannelManager.EstablishAsync completed");
        }
        catch (Exception ex)
        {
            TestContext.Out.WriteLine($"🔍 HOST SIDE - SecureChannelManager.EstablishAsync threw exception: {ex.Message}");
            TestContext.Out.WriteLine($"🔍 HOST SIDE - Exception details: {ex}");
            throw;
        }

        secureChannelResult.Match(
            onSuccess: secureChannelState =>
            {
                // Verify secure channel is established
                _ = _virtualCard.IsSecureChannelEstablished.Should().BeTrue("Secure channel should be established");
                _ = secureChannelState.SecurityLevel.Should().Be(securityLevel, "Security level should match requested level");

                TestContext.Out.WriteLine("✅ SCP03 secure channel established successfully using proper GP architecture");
            },
            onFailure: error =>
            {
                Assert.Fail($"SCP03 secure channel establishment should succeed: {error}");
            });
    }

    /// <summary>
    /// Tests pipeline handling of secure channel errors and edge cases.
    /// Validates proper error propagation and GP specification compliance.
    /// </summary>
    [Test]
    public async Task SecureChannel_ErrorHandling_ShouldComplyWithGPSpecification()
    {
        // Per GP Card Spec v2.3.1 Section 6.4.1: ISD is implicitly selected by default
        // Per GP Card Spec v2.3.1 Section 6.4.2.1.1: ISD remains selected after reset
        _virtualCard.Reset();
        _ = _virtualCard.IsSelected.Should().BeTrue("ISD is implicitly selected by default per GP Card Spec v2.3.1");

        // Test 1: INITIALIZE UPDATE should succeed with implicit selection per GP specification
        byte[] hostChallenge = GenerateHostChallenge();
        Result<CommandResponse, SmartCardError> initUpdateResult = await ExecuteInitializeUpdate(hostChallenge);

        initUpdateResult.Match(
            onSuccess: result =>
            {
                // Per GP specification, INIT UPDATE should succeed with implicit ISD selection
                _ = result.StatusWord.Should().Be(StatusWords.Success, "INIT UPDATE should succeed with implicitly selected ISD per GP Card Spec v2.3.1");
            },
            onFailure: error =>
            {
                Assert.Fail($"INIT UPDATE should succeed with implicit ISD selection: {error.Message}");
            });

        // Test 2: Verify explicit SELECT also works (but not required)
        _ = await ExecuteSelectIsd();
        Result<CommandResponse, SmartCardError> validInitResult = await ExecuteInitializeUpdate(hostChallenge);
        _ = validInitResult.IsSuccess.Should().BeTrue("INIT UPDATE should always succeed when ISD is available");

        // Test 3: EXTERNAL AUTHENTICATE with wrong cryptogram should fail
        byte[] wrongCryptogram = new byte[8]; // All zeros
        Result<CommandResponse, SmartCardError> extAuthResult = await ExecuteExternalAuthenticate(wrongCryptogram);
        _ = extAuthResult.IsSuccess.Should().BeFalse("EXTERNAL AUTHENTICATE with wrong cryptogram should fail");

        // Test 4: Protected commands without secure channel should fail
        Result<IApduCommand, SmartCardError> deleteCommand = CreateDeleteCommand();
        Result<CommandResponse, SmartCardError> deleteResult = await deleteCommand.Bind(async cmd => await ExecuteCommand(cmd));

        deleteResult.Match(
            onSuccess: _ => Assert.Fail("DELETE without secure channel should fail"),
            onFailure: error => error.StatusWord.Should().Be((StatusWord)0x6982, "Should return 'Security status not satisfied'"));

        TestContext.Out.WriteLine("✅ Error handling complies with GP 2.3.1 specification");
    }

    /// <summary>
    /// Tests protected command execution after secure channel establishment.
    /// Verifies DELETE, INSTALL, LOAD commands work with proper authentication.
    /// </summary>
    [Test]
    public async Task ProtectedCommands_WithEstablishedSecureChannel_ShouldExecuteSuccessfully()
    {
        // Establish secure channel first
        _ = await EstablishSecureChannelScp02();
        _ = _virtualCard.IsSecureChannelEstablished.Should().BeTrue("Secure channel must be established");

        // Test 1: DELETE command should succeed with secure channel
        Result<IApduCommand, SmartCardError> deleteCommand = CreateDeleteCommand();
        Result<CommandResponse, SmartCardError> deleteResult = await deleteCommand.Bind(async cmd => await ExecuteCommand(cmd));

        _ = deleteResult.Match(
            onSuccess: result =>
            {
                _ = result.StatusWord.Should().Be(StatusWords.Success);
                return result;
            },
            onFailure: error =>
            {
                Assert.Fail($"DELETE with secure channel should succeed: {error.Message}");
                return default;
            });

        // Test 2: INSTALL [for load] should succeed with secure channel
        Result<IApduCommand, SmartCardError> installCommand = CreateInstallForLoadCommand();
        Result<CommandResponse, SmartCardError> installResult = await installCommand.Bind(async cmd => await ExecuteCommand(cmd));

        _ = installResult.Match(
            onSuccess: result =>
            {
                _ = result.StatusWord.Should().Be(StatusWords.Success);
                return result;
            },
            onFailure: error =>
            {
                Assert.Fail($"INSTALL [for load] with secure channel should succeed: {error.Message}");
                return default;
            });

        // Test 3: LOAD command should succeed with secure channel
        Result<IApduCommand, SmartCardError> loadCommand = CreateLoadCommand();
        Result<CommandResponse, SmartCardError> loadResult = await loadCommand.Bind(async cmd => await ExecuteCommand(cmd));

        _ = loadResult.Match(
            onSuccess: result =>
            {
                _ = result.StatusWord.Should().Be(StatusWords.Success);
                return result;
            },
            onFailure: error =>
            {
                Assert.Fail($"LOAD with secure channel should succeed: {error.Message}");
                return default;
            });

        TestContext.Out.WriteLine("✅ Protected commands execute successfully with established secure channel");
    }

    /// <summary>
    /// Tests multiple secure channel establishments and session isolation.
    /// Verifies each session has independent cryptographic state.
    /// </summary>
    [Test]
    public async Task MultipleSecureChannels_ShouldMaintainIndependentSessions()
    {
        // Session 1: Establish first secure channel
        SessionKeys session1Keys = await EstablishSecureChannelScp02();
        bool firstSessionEstablished = _virtualCard.IsSecureChannelEstablished;
        var firstSessionState = _virtualCard.CurrentState.SecureChannel;

        // Reset card to simulate new session
        _virtualCard.Reset();
        _ = _virtualCard.IsSecureChannelEstablished.Should().BeFalse("Reset should clear secure channel state");

        // Session 2: Establish second secure channel with different challenge
        SessionKeys session2Keys = await EstablishSecureChannelScp02();
        bool secondSessionEstablished = _virtualCard.IsSecureChannelEstablished;
        var secondSessionState = _virtualCard.CurrentState.SecureChannel;

        // Verify sessions are independent
        _ = firstSessionEstablished.Should().BeTrue("First session should have been established");
        _ = secondSessionEstablished.Should().BeTrue("Second session should have been established");

        // Keys should be different since they use different challenges
        _ = session1Keys.SMac.Should().NotEqual(session2Keys.SMac, "Session MAC keys should be different due to different challenges");
        _ = session1Keys.SEnc.Should().NotEqual(session2Keys.SEnc, "Session encryption keys should be different due to different challenges");

        TestContext.Out.WriteLine("✅ Multiple secure channel sessions maintain independence");
    }

    /// <summary>
    /// Gets the current session keys that were derived during INITIALIZE UPDATE.
    /// Required for calculating proper MAC on EXTERNAL AUTHENTICATE command.
    /// </summary>
    private Result<SessionKeys, SmartCardError> GetCurrentSessionKeys()
    {
        return _lastDerivedSessionKeys.Match(
            Some: sessionKeys =>
            {
                TestContext.Out.WriteLine($"✅ Session keys found: S-MAC = {Convert.ToHexString(sessionKeys.SMac[0..4])}...");
                return Result.Success<SessionKeys, SmartCardError>(sessionKeys);
            },
            None: () =>
            {
                TestContext.Out.WriteLine($"❌ No session keys available - _lastDerivedSessionKeys is None");
                return Result.Failure<SessionKeys, SmartCardError>(
                    SmartCardError.ConditionsNotSatisfied());
            });
    }

    /// <summary>
    /// Calculates the C-MAC for EXTERNAL AUTHENTICATE command according to GlobalPlatform Card Specification v2.3.1.
    /// Per GP Card Spec v2.3.1 Section E.3.2: "SCP02 mandates the use of a MAC on the EXTERNAL AUTHENTICATE command"
    /// and "For the EXTERNAL AUTHENTICATE command MAC verification, the ICV is set to zero."
    /// MAC is calculated over command header + host cryptogram using session-derived S-MAC key.
    /// </summary>
    private Result<byte[], SmartCardError> CalculateExternalAuthenticateMac(
        byte[] hostCryptogram, SessionKeys sessionKeys)
    {
        // Per GP Card Spec v2.3.1 Section E.3.2: Construct MAC input for EXTERNAL AUTHENTICATE command
        // EXTERNAL AUTHENTICATE command format: CLA=84 INS=82 P1=SecurityLevel P2=00 LC=10 Data=HostCryptogram
        byte[] commandHeader = [0x84, 0x82, (byte)SecurityLevel.CMac, 0x00, 0x10];
        byte[] macInput = commandHeader.Concat(hostCryptogram).ToArray();

        TestContext.Out.WriteLine($"🔍 GP Card Spec v2.3.1 Section E.3.2 - EXTERNAL AUTHENTICATE MAC Calculation:");
        TestContext.Out.WriteLine($"🔍 Command Header: {Convert.ToHexString(commandHeader)}");
        TestContext.Out.WriteLine($"🔍 Host Cryptogram: {Convert.ToHexString(hostCryptogram)}");
        TestContext.Out.WriteLine($"🔍 MAC Input (Header + Cryptogram): {Convert.ToHexString(macInput)}");
        TestContext.Out.WriteLine($"🔍 Session S-MAC Key: {Convert.ToHexString(sessionKeys.SMac)}");

        // FIXED: SCP02 uses 3DES MAC, not AES-CMAC per GP Card Spec v2.3.1 Section E.4.3
        return MacCalculations.CalculateScp02CommandMac(sessionKeys.SMac, macInput)
            .Map(calculatedMac =>
            {
                TestContext.Out.WriteLine($"🔍 SCP02 3DES MAC (8 bytes): {Convert.ToHexString(calculatedMac)}");
                return calculatedMac;
            });
    }

    /// <summary>
    /// Calculates AES-CMAC using Result pattern for proper error handling.
    /// </summary>
    private Result<byte[], SmartCardError> CalculateAesCmacResult(byte[] key, byte[] data)
    {
        try
        {
            byte[] mac = CalculateAesCmac(key, data);
            return Result.Success<byte[], SmartCardError>(mac);
        }
        catch (Exception ex)
        {
            return Result.Failure<byte[], SmartCardError>(
                SmartCardError.CryptographicError($"AES-CMAC calculation failed: {ex.Message}"));
        }
    }

    // Field to store session keys between INITIALIZE UPDATE and EXTERNAL AUTHENTICATE
    private Maybe<SessionKeys> _lastDerivedSessionKeys = Maybe<SessionKeys>.None;

    /// <summary>
    /// Tests card reset behavior and secure channel cleanup.
    /// Verifies proper state management per GP specification.
    /// </summary>
    [Test]
    public async Task CardReset_ShouldClearSecureChannelState()
    {
        // Establish secure channel
        _ = await EstablishSecureChannelScp02();
        _ = _virtualCard.IsSecureChannelEstablished.Should().BeTrue("Secure channel should be established");

        // Reset card
        _virtualCard.Reset();

        // Verify secure channel state is cleared
        _ = _virtualCard.IsSecureChannelEstablished.Should().BeFalse("Secure channel should be cleared after reset");
        // Per GP Card Spec v2.3.1 Section 6.4.2.1.1: ISD remains implicitly selected after reset
        _ = _virtualCard.IsSelected.Should().BeTrue("ISD remains implicitly selected after reset per GP Card Spec v2.3.1");

        // Verify protected commands fail after reset
        Result<IApduCommand, SmartCardError> deleteCommand = CreateDeleteCommand();
        Result<CommandResponse, SmartCardError> deleteResult = await deleteCommand.Bind(async cmd => await ExecuteCommand(cmd));
        _ = deleteResult.IsSuccess.Should().BeFalse("Protected commands should fail after reset");

        TestContext.Out.WriteLine("✅ Card reset properly clears secure channel state");
    }

    // Helper methods for test implementation

    private CommandProcessing.CommandEnvironment CreatePipelineEnvironment()
    {
        // Create secure channel service for testing
        var secureChannelService = new SecureChannelService();

        // Get current secure channel state from virtual card to enable proper pipeline processing
        var secureChannelState = _virtualCard.CurrentState.SecureChannel;

        return new CommandProcessing.CommandEnvironment(
            _channel,
            _transport,
            secureChannelState,
            secureChannelService,
            _logger,
            CommandOptions.Default);
    }

    private async Task<Result<CommandResponse, SmartCardError>> ExecuteSelectIsd()
    {
        Result<SelectCommand, SmartCardError> selectCommandResult = SelectCommand.CreateForIssuerSecurityDomain();
        if (selectCommandResult.IsFailure)
            return Result.Failure<CommandResponse, SmartCardError>(selectCommandResult.Error);

        return await ExecuteCommand(selectCommandResult.Value);
    }

    private async Task<Result<CommandResponse, SmartCardError>> ExecuteInitializeUpdate(
        byte[] hostChallenge)
    {
        Result<InitializeUpdateCommand, SmartCardError> initCommandResult = InitializeUpdateCommand.Create(
                keyVersion: 0x00,
                keyIdentifier: 0x00,
                hostChallenge: hostChallenge);
        if (initCommandResult.IsFailure)
            return Result.Failure<CommandResponse, SmartCardError>(initCommandResult.Error);

        return await ExecuteCommand(initCommandResult.Value);
    }

    private async Task<Result<CommandResponse, SmartCardError>> ExecuteExternalAuthenticate(
        byte[] hostCryptogram)
    {
        // Calculate proper MAC according to GP specification instead of hardcoding zeros
        Result<SessionKeys, SmartCardError> sessionKeysResult = GetCurrentSessionKeys();

        return sessionKeysResult.Match(
            onSuccess: async sessionKeys =>
            {
                // Calculate proper C-MAC over EXTERNAL AUTHENTICATE command
                Result<byte[], SmartCardError> macResult = CalculateExternalAuthenticateMac(hostCryptogram, sessionKeys);

                return await macResult.Match(
                    onSuccess: async calculatedMac =>
                    {
                        TestContext.Out.WriteLine($"🔍 Using calculated MAC: {Convert.ToHexString(calculatedMac)}");
                        Result<ExternalAuthenticateCommand, SmartCardError> extAuthCommandResult = ExternalAuthenticateCommand.CreateWithMac(
                                securityLevel: SecurityLevel.CMac,
                                hostCryptogram: hostCryptogram,
                                mac: calculatedMac);
                        return await extAuthCommandResult.Match(
                            onSuccess: async command => await ExecuteCommand(command),
                            onFailure: error => Task.FromResult(Result.Failure<CommandResponse, SmartCardError>(error)));
                    },
                    onFailure: error =>
                    {
                        TestContext.Out.WriteLine($"❌ MAC calculation failed: {error}");
                        return Task.FromResult(Result.Failure<CommandResponse, SmartCardError>(error));
                    });
            },
            onFailure: async error =>
            {
                TestContext.Out.WriteLine($"❌ Failed to get session keys for MAC calculation: {error}");
                return Result.Failure<CommandResponse, SmartCardError>(
                    SmartCardError.CryptographicError("Session keys not available for MAC calculation"));
            }).GetAwaiter().GetResult();
    }

    private async Task<Result<CommandResponse, SmartCardError>> ExecuteCommand(
        IApduCommand command)
    {
        // Create pipeline processor with secure channel enabled
        CommandProcessing.CommandProcessor? processor = Pipeline.CommandProcessors.CreatePipeline(enableLogging: true, enableSecureChannel: true);

        // Get current environment and sync with virtual card secure channel state
        CommandProcessing.CommandEnvironment environment = CreatePipelineEnvironment();
        CommandProcessing.CommandEnvironment updatedEnvironment = (_transport as VirtualCardTransport)?.CreateUpdatedEnvironment(environment) ?? environment;

        SmartCardService service = new SmartCardService(updatedEnvironment, processor, _logger as ILogger<SmartCardService>);
        return await service.ExecuteCommandAsync(command, CancellationToken.None);
    }

    private byte[] GenerateHostChallenge()
    {
        // Use fixed deterministic host challenge so virtual card can consume entropy sequentially
        // This ensures host challenge (bytes 0-7) != card challenge (bytes 8-13) for proper SCP02 testing
        return [0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08];
    }

    private Result<SessionKeys, SmartCardError> DeriveSessionKeys(
        byte keyVersion, byte[] hostChallenge, byte[] cardChallenge)
    {
        // Get static keys from virtual card configuration
        return _virtualCard.Configuration.StaticKeys.TryGetValue(keyVersion, out IKeySet? keySet) && keySet is Scp02KeySet scp02KeySet
            ? DeriveSessionKeysFromScp02KeySet(scp02KeySet, hostChallenge, cardChallenge)
            : Result.Failure<SessionKeys, SmartCardError>(
                SmartCardError.CryptographicError("Failed to retrieve static keys for session derivation"));
    }

    private Result<SessionKeys, SmartCardError> DeriveSessionKeysFromScp02KeySet(
        Scp02KeySet scp02KeySet, byte[] hostChallenge, byte[] cardChallenge)
    {
        // ELIMINATE DRY VIOLATION: Use the same production KeyDerivationService that the virtual card uses
        // This ensures identical session key derivation logic between test and virtual card
        TestContext.Out.WriteLine($"🔍 Using production KeyDerivationService (same as virtual card)");
        TestContext.Out.WriteLine($"🔍 Host Challenge: {Convert.ToHexString(hostChallenge)} ({hostChallenge.Length} bytes)");
        TestContext.Out.WriteLine($"🔍 Card Challenge: {Convert.ToHexString(cardChallenge)} ({cardChallenge.Length} bytes)");
        TestContext.Out.WriteLine($"🔍 SCP Version: 0x02");

        // Use the same sequence counter as the virtual card (from INITIALIZE UPDATE response)
        byte[] sequenceCounter = [0x00, 0x01]; // Fixed sequence counter that virtual card uses

        // Create key derivation context exactly like virtual card does
        Result<KeyDerivationContext, SmartCardError> contextResult = KeyDerivationContext.CreateForScp02(
            scp02KeySet,
            hostChallenge,
            cardChallenge,
            sequenceCounter,
            ScpImplementation.Scp02I15); // P71 cards use i=15

        if (contextResult.IsFailure)
        {
            return Result.Failure<SessionKeys, SmartCardError>(contextResult.Error);
        }

        // Use the same production KeyDerivationService that the virtual card uses
        KeyDerivationService keyDerivationService = new KeyDerivationService();
        Result<SessionKeys, SmartCardError> result = keyDerivationService.DeriveSessionKeys(contextResult.Value);

        return result.Match(
            sessionKeys =>
            {
                TestContext.Out.WriteLine($"🔍 Derived S-ENC: {Convert.ToHexString(sessionKeys.SEnc)}");
                TestContext.Out.WriteLine($"🔍 Derived S-MAC: {Convert.ToHexString(sessionKeys.SMac)}");
                return Result.Success<SessionKeys, SmartCardError>(sessionKeys);
            },
            error => Result.Failure<SessionKeys, SmartCardError>(error));
    }

    private Result<SessionKeys, SmartCardError> DeriveSessionKeysScp03(
        byte keyVersion, byte[] hostChallenge, byte[] cardChallenge)
    {
        // SCP03 session key derivation - different algorithm from SCP02
        return _virtualCard.Configuration.StaticKeys.TryGetValue(keyVersion, out IKeySet? keySet) && keySet is Scp03KeySet scp03KeySet
            ? DeriveSessionKeysFromScp03KeySet(scp03KeySet, hostChallenge, cardChallenge)
            : Result.Failure<SessionKeys, SmartCardError>(
                SmartCardError.CryptographicError("Failed to retrieve SCP03 static keys"));
    }

    private Result<SessionKeys, SmartCardError> DeriveSessionKeysFromScp03KeySet(
        Scp03KeySet scp03KeySet, byte[] hostChallenge, byte[] cardChallenge)
    {
        // FIXED: Use production key derivation service instead of simplified AES derivation
        // This ensures the test uses the same key derivation as the virtual card
        KeyDerivationService keyDerivationService = new KeyDerivationService();

        return KeyDerivationContext.CreateForScp03(
                scp03KeySet,
                hostChallenge,
                cardChallenge,
                Maybe<ScpImplementation>.From(ScpImplementation.Scp03I70))
            .Bind(context => keyDerivationService.DeriveSessionKeys(context));
    }

    private Result<byte[], SmartCardError> CalculateAndVerifyCryptograms(
        SessionKeys sessionKeys, byte[] hostChallenge, byte[] cardChallenge, byte[] cardCryptogram, byte[] sequenceCounter)
    {
        // Debug output to understand what we're passing to cryptogram service
        TestContext.Out.WriteLine($"🔍 Cryptogram calculation parameters:");
        TestContext.Out.WriteLine($"🔍 Host Challenge Length: {hostChallenge.Length} bytes - {Convert.ToHexString(hostChallenge)}");
        TestContext.Out.WriteLine($"🔍 Card Challenge Length: {cardChallenge.Length} bytes - {Convert.ToHexString(cardChallenge)}");
        TestContext.Out.WriteLine($"🔍 Sequence Counter Length: {sequenceCounter.Length} bytes - {Convert.ToHexString(sequenceCounter)}");
        TestContext.Out.WriteLine($"🔍 Card Cryptogram Length: {cardCryptogram.Length} bytes - {Convert.ToHexString(cardCryptogram)}");

        // Use the same cryptographic service that the virtual card uses for consistency
        CryptogramService cryptoService = new CryptogramService();

        // For SCP02, calculate expected card cryptogram using type-safe parameters
        Result<byte[], SmartCardError> expectedCryptogramResult = Scp02KeySet.Create(sessionKeys.SEnc, sessionKeys.SMac, sessionKeys.Dek)
            .Bind(keySet => CryptogramParameters.ForScp02(
                hostChallenge,
                cardChallenge,
                sequenceCounter, // Use actual sequence counter from INITIALIZE UPDATE response
                keySet))
            .Bind(parameters => cryptoService.CalculateCardCryptogram(parameters));

        return expectedCryptogramResult.Match(
            expectedCryptogram =>
            {
                // Debug cryptogram comparison
                byte[] calculatedFirst8 = expectedCryptogram.Take(8).ToArray();
                TestContext.Out.WriteLine($"🔍 Calculated card cryptogram: {Convert.ToHexString(calculatedFirst8)}");
                TestContext.Out.WriteLine($"🔍 Virtual card cryptogram:   {Convert.ToHexString(cardCryptogram)}");
                TestContext.Out.WriteLine($"🔍 Cryptograms match: {calculatedFirst8.SequenceEqual(cardCryptogram)}");

                // Verify card cryptogram matches (first 8 bytes)
                return calculatedFirst8.SequenceEqual(cardCryptogram)
                    ? CalculateHostCryptogramScp02(cryptoService, sessionKeys, hostChallenge, cardChallenge, sequenceCounter)
                    : Result.Failure<byte[], SmartCardError>(
                        SmartCardError.AuthenticationFailed("Card cryptogram verification failed"));
            },
            error => Result.Failure<byte[], SmartCardError>(error));
    }

    private Result<byte[], SmartCardError> CalculateHostCryptogramScp02(
        CryptogramService cryptoService,
        SessionKeys sessionKeys,
        byte[] hostChallenge,
        byte[] cardChallenge,
        byte[] sequenceCounter)
    {
        // FIXED: Both virtual card and test now use SESSION keys for consistency
        // Virtual card now properly derives session keys first in CryptographicService
        // Use the same session keys that the virtual card derives
        TestContext.Out.WriteLine($"🔍 Using session key for host cryptogram (matching virtual card approach)");
        TestContext.Out.WriteLine($"🔍 Session S-ENC key: {Convert.ToHexString(sessionKeys.SEnc)}");

        return Scp02KeySet.Create(sessionKeys.SEnc, sessionKeys.SMac, sessionKeys.Dek)
            .Bind(keySet => CryptogramParameters.ForScp02(
                hostChallenge,
                cardChallenge,
                sequenceCounter,
                keySet))
            .Bind(parameters => cryptoService.CalculateHostCryptogram(parameters));
    }

    // REMOVED: This was a simplified implementation that should not be used

    private Result<byte[], SmartCardError> CalculateAndVerifyCryptogramsScp03(
        SessionKeys sessionKeys, byte[] hostChallenge, byte[] cardChallenge, byte[] cardCryptogram)
    {
        // FIXED: Use production CryptogramService instead of simplified AES-CMAC
        // SCP03 uses GP SCP03 v1.1.1 data derivation scheme, not direct AES-CMAC
        CryptogramService cryptoService = new CryptogramService();

        // DEBUG: Log all cryptogram calculation parameters
        TestContext.Out.WriteLine($"🔍 SCP03 Cryptogram Calculation Debug:");
        TestContext.Out.WriteLine($"🔍 Host Challenge: {Convert.ToHexString(hostChallenge)} ({hostChallenge.Length} bytes)");
        TestContext.Out.WriteLine($"🔍 Card Challenge: {Convert.ToHexString(cardChallenge)} ({cardChallenge.Length} bytes)");
        TestContext.Out.WriteLine($"🔍 S-MAC Key: {Convert.ToHexString(sessionKeys.SMac)} ({sessionKeys.SMac.Length} bytes)");
        TestContext.Out.WriteLine($"🔍 Context (Host||Card): {Convert.ToHexString(hostChallenge.Concat(cardChallenge).ToArray())}");

        Result<byte[], SmartCardError> cardCryptogramResult = Scp03KeySet.Create(sessionKeys.SEnc, sessionKeys.SMac, sessionKeys.Dek)
            .Bind(keySet => CryptogramParameters.ForScp03(hostChallenge, cardChallenge, keySet))
            .Bind(parameters => cryptoService.CalculateCardCryptogram(parameters));

        return cardCryptogramResult.Bind(expectedCardCryptogram =>
        {
            TestContext.Out.WriteLine($"🔍 SCP03 Card Cryptogram Verification:");
            TestContext.Out.WriteLine($"🔍 Virtual card cryptogram: {Convert.ToHexString(cardCryptogram)}");
            TestContext.Out.WriteLine($"🔍 Test calculated:         {Convert.ToHexString(expectedCardCryptogram)}");
            TestContext.Out.WriteLine($"🔍 Match: {expectedCardCryptogram.SequenceEqual(cardCryptogram)}");

            return expectedCardCryptogram.SequenceEqual(cardCryptogram)
                ? CalculateHostCryptogramScp03(sessionKeys, hostChallenge, cardChallenge)
                : Result.Failure<byte[], SmartCardError>(
                    SmartCardError.AuthenticationFailed("SCP03 card cryptogram verification failed"));
        });
    }

    private Result<byte[], SmartCardError> CalculateHostCryptogramScp03(
        SessionKeys sessionKeys, byte[] hostChallenge, byte[] cardChallenge)
    {
        // FIXED: Use production CryptogramService for SCP03 host cryptogram
        // SCP03 uses GP SCP03 v1.1.1 data derivation scheme, not direct AES-CMAC
        CryptogramService cryptoService = new CryptogramService();

        return Scp03KeySet.Create(sessionKeys.SEnc, sessionKeys.SMac, sessionKeys.Dek)
            .Bind(keySet => CryptogramParameters.ForScp03(hostChallenge, cardChallenge, keySet))
            .Bind(parameters => cryptoService.CalculateHostCryptogram(parameters));
    }

    /// <summary>
    /// Establishes SCP02 secure channel and stores session keys for MAC calculations.
    /// Per GP Card Spec v2.3.1 Section 6.4.1.1: Complete SELECT → INITIALIZE UPDATE → EXTERNAL AUTHENTICATE sequence.
    /// </summary>
    private async Task<SessionKeys> EstablishSecureChannelScp02()
    {
        // Complete SCP02 secure channel establishment sequence
        Result<CommandResponse, SmartCardError> selectResult = await ExecuteSelectIsd();
        if (selectResult.IsFailure)
        {
            Assert.Fail($"SELECT ISD failed: {selectResult.Error}");
            return default!;
        }

        byte[] hostChallenge = GenerateHostChallenge();
        Result<CommandResponse, SmartCardError> initResult = await ExecuteInitializeUpdate(hostChallenge);

        if (initResult.IsSuccess)
        {
            CommandResponse? initResponse = initResult.Value;

            // Parse INITIALIZE UPDATE response using functional pattern
            Result<InitializeUpdateResponse, SmartCardError> parseResult = InitializeUpdateResponse.Parse(initResponse.Data);
            if (parseResult.IsSuccess)
            {
                InitializeUpdateResponse? response = parseResult.Value;

                // Derive session keys using functional approach
                Result<SessionKeys, SmartCardError> sessionKeysResult = DeriveSessionKeys(response.KeyVersion, hostChallenge, response.CardChallenge);
                if (sessionKeysResult.IsSuccess)
                {
                    SessionKeys? sessionKeys = sessionKeysResult.Value;

                    // Store session keys BEFORE external authenticate for MAC calculation
                    _lastDerivedSessionKeys = Maybe<SessionKeys>.From(sessionKeys);
                    TestContext.Out.WriteLine($"✅ Session keys stored before EXTERNAL AUTHENTICATE: S-MAC = {Convert.ToHexString(sessionKeys.SMac[0..4])}...");

                    // Calculate and verify cryptograms
                    Result<byte[], SmartCardError> hostCryptogramResult = CalculateAndVerifyCryptograms(
                        sessionKeys, hostChallenge, response.CardChallenge, response.CardCryptogram, response.SequenceCounter);

                    if (hostCryptogramResult.IsSuccess)
                    {
                        byte[]? hostCryptogram = hostCryptogramResult.Value;

                        // Execute EXTERNAL AUTHENTICATE with proper MAC
                        Result<CommandResponse, SmartCardError> extAuthResult = await ExecuteExternalAuthenticate(hostCryptogram);
                        if (extAuthResult.IsSuccess)
                        {
                            TestContext.Out.WriteLine($"✅ SCP02 secure channel established successfully");
                            return sessionKeys;
                        }
                        else
                        {
                            Assert.Fail($"EXTERNAL AUTHENTICATE failed: {extAuthResult.Error}");
                        }
                    }
                    else
                    {
                        Assert.Fail($"Cryptogram calculation failed: {hostCryptogramResult.Error}");
                    }
                }
                else
                {
                    Assert.Fail($"Session key derivation failed: {sessionKeysResult.Error}");
                }
            }
            else
            {
                Assert.Fail($"Failed to parse INITIALIZE UPDATE response: {parseResult.Error}");
            }
        }
        else
        {
            Assert.Fail($"INITIALIZE UPDATE failed: {initResult.Error}");
        }

        return default!;
    }

    private async Task VerifyProtectedCommandsWork()
    {
        // Test that protected commands work with established secure channel
        Result<IApduCommand, SmartCardError> deleteCommand = CreateDeleteCommand();
        Result<CommandResponse, SmartCardError> deleteResult = await deleteCommand.Bind(async cmd => await ExecuteCommand(cmd));
        _ = deleteResult.IsSuccess.Should().BeTrue("DELETE should work with secure channel");

        Result<IApduCommand, SmartCardError> installCommand = CreateInstallForLoadCommand();
        Result<CommandResponse, SmartCardError> installResult = await installCommand.Bind(async cmd => await ExecuteCommand(cmd));
        _ = installResult.IsSuccess.Should().BeTrue("INSTALL should work with secure channel");
    }

    private Result<IApduCommand, SmartCardError> CreateDeleteCommand()
    {
        byte[] testAid = Convert.FromHexString("A00000030800001000");
        return DeleteCommand.CreateForApplication(testAid, deleteRelated: true)
            .Map(cmd => (IApduCommand)cmd);
    }

    private Result<IApduCommand, SmartCardError> CreateInstallForLoadCommand()
    {
        byte[] packageAid = Convert.FromHexString("A000000308000010");
        return InstallCommandBuilder.CreateForLoad(packageAid, _virtualCard.Configuration.IsdAid)
            .Map(cmd => (IApduCommand)cmd);
    }

    private Result<IApduCommand, SmartCardError> CreateLoadCommand()
    {
        // Create minimal LOAD command for testing
        byte[] loadData = [0x01, 0x02, 0x03, 0x04]; // Minimal CAP file data
        return LoadCommand.Create(blockNumber: 0, data: loadData, isLastBlock: true)
            .Map(cmd => (IApduCommand)cmd);
    }

    private byte[] DeriveKey(byte[] staticKey, byte[] derivationData, byte keyType)
    {
        // Simplified 3DES key derivation for testing
        byte[] input = new byte[16];
        Array.Copy(derivationData, 0, input, 0, Math.Min(derivationData.Length, 15));
        input[15] = keyType;

        // Use BouncyCastle 3DES
        DesEdeEngine engine = new Org.BouncyCastle.Crypto.Engines.DesEdeEngine();
        byte[] expandedKey = staticKey.Length == 16
            ? staticKey.Concat(staticKey[..8]).ToArray()
            : staticKey;

        engine.Init(true, new Org.BouncyCastle.Crypto.Parameters.KeyParameter(expandedKey));

        byte[] output = new byte[16];
        _ = engine.ProcessBlock(input, 0, output, 0);
        _ = engine.ProcessBlock(input, 8, output, 8);

        return output;
    }

    /// <summary>
    /// Gets the SCP03 key set from virtual card configuration for host-side processing.
    /// </summary>
    private Result<Scp03KeySet, SmartCardError> GetScp03KeySetFromVirtualCard()
    {
        // Retrieve SCP03 key set from virtual card configuration
        // This matches the keys that the virtual card uses for card-side processing
        Scp03KeySet[] scp03Keys = _virtualCard.Configuration.StaticKeys.Values
            .OfType<Scp03KeySet>()
            .ToArray();

        return scp03Keys.Length > 0
            ? Result.Success<Scp03KeySet, SmartCardError>(scp03Keys.First())
            : Result.Failure<Scp03KeySet, SmartCardError>(
                SmartCardError.CryptographicError("No SCP03 key set found in virtual card configuration"));
    }

    private byte[] CalculateMac(byte[] key, byte[] data)
    {
        // Simplified MAC calculation using 3DES
        DesEdeEngine engine = new Org.BouncyCastle.Crypto.Engines.DesEdeEngine();
        byte[] expandedKey = key.Length == 16 ? key.Concat(key[..8]).ToArray() : key;

        engine.Init(true, new Org.BouncyCastle.Crypto.Parameters.KeyParameter(expandedKey));

        // Pad data to multiple of 16 bytes
        int paddedLength = ((data.Length + 15) / 16) * 16;
        byte[] paddedData = new byte[paddedLength];
        Array.Copy(data, paddedData, data.Length);

        // Process data in 16-byte blocks using functional approach
        return Enumerable.Range(0, paddedLength / 16)
            .Select(i => i * 16)
            .Aggregate(new byte[16], (mac, offset) =>
            {
                byte[] result = new byte[16];
                _ = engine.ProcessBlock(paddedData, offset, result, 0);
                return result;
            });
    }

    private byte[] CalculateAesCmac(byte[] key, byte[] data)
    {
        // Simplified AES-CMAC for SCP03
        AesEngine engine = new Org.BouncyCastle.Crypto.Engines.AesEngine();
        engine.Init(true, new Org.BouncyCastle.Crypto.Parameters.KeyParameter(key));

        // Pad data
        int paddedLength = ((data.Length + 15) / 16) * 16;
        byte[] paddedData = new byte[paddedLength];
        Array.Copy(data, paddedData, data.Length);
        if (data.Length < paddedLength)
        {
            paddedData[data.Length] = 0x80; // Padding
        }

        // Process blocks using functional approach
        return Enumerable.Range(0, paddedLength / 16)
            .Select(i => i * 16)
            .Aggregate(new byte[16], (cmac, offset) =>
            {
                // XOR block with current CMAC
                byte[] blockXorCmac = Enumerable.Range(0, 16)
                    .Select(j => (byte)(cmac[j] ^ paddedData[offset + j]))
                    .ToArray();

                byte[] result = new byte[16];
                _ = engine.ProcessBlock(blockXorCmac, 0, result, 0);
                return result;
            });
    }
}

/// <summary>
/// Extension methods for VirtualCardTestBuilder to support additional configurations.
/// </summary>
public static class VirtualCardTestBuilderExtensions
{
    /// <summary>
    /// Creates an SCP03-capable virtual card for testing.
    /// </summary>
    public static VirtualCard Scp03Card()
    {
        return VirtualCardTestBuilder.Builder()
            .WithConfiguration(CardConfiguration.Scp03First())
            .WithTestCrypto()
            .Build();
    }
}


