<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="../src/Gp4Net/Gp4Net.csproj" />
  </ItemGroup>
</Project>