// -----------------------------------------------------------------------------
// Copyright (c) 2025 Mistial Developer <opensource@mistial.dev>
// SPDX-License-Identifier: AGPL-3.0-only
// -----------------------------------------------------------------------------

using JetBrains.Annotations;

namespace Gp4Net.Constants;

public static partial class Constants
{
    /// <summary>
    /// Security and secure channel constants for GlobalPlatform protocols.
    /// Consolidates ALL security-related constants from SecurityConstants.cs
    /// Reference: GlobalPlatform Card Specification v2.3.1 and SCP03 v1.1.1
    /// </summary>
    [PublicAPI]
    public static class Security
    {
        /// <summary>
        /// Session establishment and challenge/response lengths.
        /// Reference: GP Card Specification v2.3.1, Sections 6.2 and 6.3
        /// </summary>
        public static class SessionParameters
        {
            /// <summary>
            /// Session identifier length in bytes (8 bytes).
            /// Used to identify the secure channel session between card and host.
            /// Reference: GP Card Specification v2.3.1, Section 6.2.1
            /// </summary>
            public const int SessionIdLength = 8;

            /// <summary>
            /// Host challenge length for secure channel establishment (8 bytes).
            /// Random value generated by host to prevent replay attacks.
            /// Reference: GP Card Specification v2.3.1, Section 6.2.2
            /// </summary>
            public const int HostChallengeLength = 8;

            /// <summary>
            /// Card challenge length for secure channel establishment (8 bytes).
            /// Random value generated by card to prevent replay attacks.
            /// Reference: GP Card Specification v2.3.1, Section 6.2.2
            /// </summary>
            public const int CardChallengeLength = 8;

            /// <summary>
            /// Key diversification data length in INITIALIZE UPDATE response (10 bytes).
            /// Used to derive session keys from static keys.
            /// Reference: GP Card Specification v2.3.1, Section 6.2.3
            /// </summary>
            public const int KeyDiversificationDataLength = 10;

            /// <summary>
            /// Standard length for cryptographic nonces (16 bytes).
            /// Used in SCP03 for IV generation and key derivation.
            /// Reference: GP SCP03 v1.1.1, Section 4.1
            /// </summary>
            public const int NonceLength = 16;
        }

        /// <summary>
        /// Authentication cryptogram lengths for mutual authentication.
        /// Reference: GP Card Specification v2.3.1, Section 6.3
        /// </summary>
        public static class AuthenticationCryptograms
        {
            /// <summary>
            /// Host cryptogram length for authentication (8 bytes).
            /// Proves host knowledge of session keys to the card.
            /// Reference: GP Card Specification v2.3.1, Section 6.3.1
            /// </summary>
            public const int HostCryptogramLength = 8;

            /// <summary>
            /// Card cryptogram length for authentication (8 bytes).
            /// Proves card knowledge of session keys to the host.
            /// Reference: GP Card Specification v2.3.1, Section 6.3.1
            /// </summary>
            public const int CardCryptogramLength = 8;

            /// <summary>
            /// Receipt MAC length for response verification (8 bytes).
            /// Used to verify response integrity in secure channels.
            /// Reference: GP Card Specification v2.3.1, Section 6.4
            /// </summary>
            public const int ReceiptMacLength = 8;
        }

        /// <summary>
        /// Protocol response and command lengths.
        /// Reference: GP Card Specification v2.3.1, Appendix B
        /// </summary>
        public static class ResponseLengths
        {
            /// <summary>
            /// INITIALIZE UPDATE response length for SCP02/SCP03 (28 bytes).
            /// Standard response containing diversification data, cryptogram, and key info.
            /// Reference: GP Card Specification v2.3.1, Section B.2.1
            /// </summary>
            public const int InitializeUpdateResponseLength = 28;
        }

        /// <summary>
        /// Key version constants for secure channel key management.
        /// Reference: GP Card Specification v2.3.1, Section 4.1.2
        /// </summary>
        public static class KeyVersions
        {
            /// <summary>
            /// Minimum secure channel key version (0x01).
            /// Lowest acceptable key version for production use.
            /// Reference: GP Card Specification v2.3.1, Section 4.1.2
            /// </summary>
            public const byte MinKeyVersion = 0x01;

            /// <summary>
            /// Maximum secure channel key version (0xFF).
            /// Highest possible key version value.
            /// Reference: GP Card Specification v2.3.1, Section 4.1.2
            /// </summary>
            public const byte MaxKeyVersion = 0xFF;

            /// <summary>
            /// Factory default key version (0xFF).
            /// Typically used for test keys and development environments.
            /// Reference: GP Card Specification v2.3.1, Section 4.1.2
            /// </summary>
            public const byte FactoryKeyVersion = 0xFF;
        }
    }
}